This is my R file about Q3 FEC filings in Mayland's Senate and House D6 race

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Turn off scientific notation
options(scipen=999)

# Load the tidyverse
library(tidyverse)
```

Load data
```{r}
AlsobrooksQ3Contribs <- read_csv("MD_Q3_FEC/AlsobrooksQ3Contribs.csv")
AlsobrooksQ3Expenses <- read_csv("MD_Q3_FEC/AlsobrooksQ3Expenses.csv")
HoganQ3Contribs <-read_csv("MD_Q3_FEC/HoganQ3Contribs.csv")
HoganQ3Expenses <- read_csv("MD_Q3_FEC/HoganQ3Expenses.csv")
DelaneyQ3Contribs <-read_csv("MD_Q3_FEC/DelaneyQ3Contribs.csv")
DelaneyQ3Expenses <- read_csv("MD_Q3_FEC/DelaneyQ3Expenses.csv")
ParrottQ3Contribs <- read_csv("MD_Q3_FEC/ParrottQ3Contribs.csv")
ParrottQ3Expenses <- read_csv("MD_Q3_FEC/ParrottQ3Expenses.csv")
md_voters_for_match <- read.csv("md_voters_for_match.csv")
```

Cleaning -------------------------------
Changing zip codes to characters

```{r}
md_voters_for_match<-md_voters_for_match|>
mutate(ResidentialZip = as.character(ResidentialZip))
glimpse(md_voters_for_match)
```
Alsobrooks donors names to uppercase
```{r}
AlsobrooksQ3Contribs<-AlsobrooksQ3Contribs|>
mutate(first_name = toupper(first_name))|>
mutate(last_name = toupper(last_name))
```

HOGAN-----------------------------------
Joining MD voter file and Hogan donations
```{r}
hogan_contribs_and_voters <- md_voters_for_match |> inner_join(HoganQ3Contribs, join_by(FirstName == first_name, LastName == last_name, ResidentialZip == zip))
glimpse(hogan_contribs_and_voters)
```
Grouping by party / donor 
```{r}
hogan_contribs_and_voters |>
  group_by(Party) |> 
  summarise(
    count=n_distinct(VTR_ID)
  ) |>
  arrange(desc(count))
```
```{r}
1408+318+292+10+7+5+2
```
```{r}
1408/2042
(2042-1408)/2042
```


Alsobrooks -------------------------------

Joining MD voter file and Alsobrooks donations
```{r}
alsobrooks_contribs_and_voters <- md_voters_for_match |> inner_join(AlsobrooksQ3Contribs, join_by(FirstName == first_name, LastName == last_name, ResidentialZip == zip))
glimpse(alsobrooks_contribs_and_voters)
```


```{r}
alsobrooks_contribs_and_voters |>
  group_by(Party) |>
  summarise(
    count = n_distinct(VTR_ID)
  )|>
  arrange(desc(count))
```
```{r}
6394+276+91+8+3+3+2
```

```{r}
6394/6777
(6777-6394)/6777
```

